package com.sample.accounting;

import com.sample.accounting.gateway.drools.DroolsAccountingRule;


// ----------
rule "both->expand->businessGroup"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "businessGroup")
then
    modify(dar) {
        setResult("no, na, na")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end


// ----------
rule "both->expand->businessUnit"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "businessUnit")
then
    modify(dar) {
        setResult("na, businessGroup, ALL")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end

// ----------
rule "both->expand->product"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "product")
then
    modify(dar) {
        setResult("na, businessUnit, ALL")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end


// ----------
rule "both->expand->channel"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "channel")
then
    modify(dar) {
        setResult("no, na, na")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end


// ----------
rule "both->expand->market"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "market")
then
    modify(dar) {
        setResult("na, channel, ALL")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end


// ----------
rule "both->expand->buyer"
ruleflow-group "expand"
when
    dar: DroolsAccountingRule(category == "buyer")
then
    modify(dar) {
        setResult("yes, na, na")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end
