package com.sample.accounting;

import com.sample.accounting.gateway.drools.DroolsAccountingRule;


// ----------
rule "product->merge"
ruleflow-group "merge"
when
    dar: DroolsAccountingRule(dimension == "product")
then
    modify(dar) {
        setResult("channel, market, buyer, businessGroup, businessUnit, product, subCatalog, catalog")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end

