package com.sample.accounting;

import com.sample.accounting.gateway.drools.DroolsAccountingRule;

// ----------
rule "product->path"
ruleflow-group "path"
when
    dar: DroolsAccountingRule(dimension == "product")
then
    modify(dar) {
        setResult("workHours, workHoursNoneBG, accountingMerge, product, businessUnit, businessGroup, buyer, market, channel")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end

rule "channel->path"
ruleflow-group "path"
when
    dar: DroolsAccountingRule(dimension == "channel")
then
    modify(dar) {
        setResult("buyer, market, channel, product, businessUnit, businessGroup")
    }
    System.out.println("rule [" + drools.getRule().getName()+ "] is fired.");
end
